[build]
publish = "public"
functions = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/meli.la/*"
to = "/.netlify/functions/offer/:splat"
status = 200
